name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t todo-list-app:latest .

      - name: Run Docker container
        run: |
          docker run -d -p 5000:5000 --name todo-app todo-list-app:latest

      - name: Test application
        run: |
          sleep 5
          curl --fail http://localhost:5000/ || exit 1
          curl --fail http://localhost:5000/tasks || exit 1

      - name: Stop and clean up
        if: always()
        run: |
          docker stop todo-app
          docker rm todo-app

      - name: Push to Docker Hub
        run: |
          docker tag todo-list-app:latest ${{ secrets.DOCKER_USERNAME }}/todo-list-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/todo-list-app:latest
